<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE CFXML [
            <!ELEMENT CFXML (thisDocumentGenerationDateTime,thisDocumentIdentifier,CFData)>
            <!ELEMENT thisDocumentGenerationDateTime (DateTimeStamp)>
            <!ELEMENT thisDocumentIdentifier (ProprietaryDocumentIdentifier)>
            <!ELEMENT CFData (ProprietaryInformation*,ProductLineItem+,CFReportBLOB?)>
            <!ELEMENT DateTimeStamp (#PCDATA)>
            <!ELEMENT ProprietaryDocumentIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryInformation (Name,Value)>
            <!ELEMENT ProductLineItem (  ProductLineNumber , TransactionType , CPUSIUvalue , ConfigurationControlNumber?, ProprietaryGroupIdentifier , ServicePacLineNumberReference? , Quantity  , ProductIdentification , UnitListPrice? , MaintenanceUnitListPrice? , ProductSubLineItem* ) >
            <!ELEMENT CFReportBLOB  (#PCDATA)>
            <!ELEMENT Name  (#PCDATA)>
            <!ELEMENT Value (#PCDATA)>
            <!ELEMENT CPUSIUvalue (#PCDATA)>
            <!ELEMENT ConfigurationControlNumber (#PCDATA)>
            <!ELEMENT ProductLineNumber (#PCDATA)>
            <!ELEMENT ProprietaryGroupIdentifier (#PCDATA)>
            <!ELEMENT ServicePacLineNumberReference (#PCDATA)>
            <!ELEMENT Quantity (#PCDATA)>
            <!ELEMENT TransactionType (#PCDATA)>
            <!ELEMENT ProductIdentification (PartnerProductIdentification*) >
            <!ELEMENT ProductSubLineItem ( LineNumber, TransactionType, Quantity , ExchangeAddSubLineItemNumber? , ProductIdentification, UnitListPrice?,MaintenanceUnitListPrice?)>
            <!ELEMENT UnitListPrice ( FinancialAmount, PriceTerm)>
            <!ELEMENT MaintenanceUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT PartnerProductIdentification ( OrderedProductIdentifier?, ProprietaryProductIdentifier, ProductDescription?, ProductTypeCode?, ProductIdentifierTypeCode?) >
            <!ELEMENT LineNumber (#PCDATA)>
            <!ELEMENT ExchangeAddSubLineItemNumber (#PCDATA)>
            <!ELEMENT FinancialAmount ( GlobalCurrencyCode, MonetaryAmount )>
            <!ELEMENT PriceTerm (#PCDATA)>
            <!ELEMENT OrderedProductIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryProductIdentifier (#PCDATA)>
            <!ELEMENT ProductDescription (#PCDATA)>
            <!ELEMENT ProductTypeCode (#PCDATA)>
            <!ELEMENT ProductIdentifierTypeCode (#PCDATA)>
            <!ELEMENT GlobalCurrencyCode (#PCDATA)>
            <!ELEMENT MonetaryAmount (#PCDATA)>
            
]>
<CFXML>
  <thisDocumentGenerationDateTime>
    <DateTimeStamp>2020-05-05T12:51:35+00:00</DateTimeStamp>
  </thisDocumentGenerationDateTime>
  <thisDocumentIdentifier>
    <ProprietaryDocumentIdentifier>CFXML.2076_624_tyw7_1_.2020-05-05T00:00:00+00:00</ProprietaryDocumentIdentifier>
  </thisDocumentIdentifier>
  <CFData>
    <ProprietaryInformation>
      <Name>CFXML</Name>
      <Value>1.0</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Configurator Identifier</Name>
      <Value>ECMSSD.90501a201200</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Price File Date</Name>
      <Value>2020-05-05</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Checksum</Name>
      <Value>3027709730</Value>
    </ProprietaryInformation>
    <ProductLineItem>
      <ProductLineNumber>1000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>1</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>2076-624</ProprietaryProductIdentifier>
          <ProductDescription>2076-624 #1:IBM Storwize V7000 SFF Control Enclosure</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>41126,00</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <MaintenanceUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>365,12</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>M</PriceTerm>
      </MaintenanceUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>1001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>8</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>5305</ProprietaryProductIdentifier>
            <ProductDescription>5m Fiber Cable (LC)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>144,50</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9730</ProprietaryProductIdentifier>
            <ProductDescription>Power Cord - PDU connection</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>29,28</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ADN1</ProprietaryProductIdentifier>
            <ProductDescription>Order Type 1 - CTO</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1004</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AGBL</ProprietaryProductIdentifier>
            <ProductDescription>Shipping and Handling</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>422,27</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1005</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AHB3</ProprietaryProductIdentifier>
            <ProductDescription>16Gb FC 4 Port Adapter Pair</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>9547,30</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>2000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>5639-CB8</ProprietaryProductIdentifier>
          <ProductDescription>IBM Spectrum Virtualize Software for Storwize V7000 Controller Software V8</ProductDescription>
          <ProductTypeCode>Software</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>2001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>UDLBC1</ProprietaryProductIdentifier>
            <ProductDescription>IBM Storwize V7000 Controller Full Feature SW with 1 Year SW Maintenance, Per Storage Device</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>3784,00</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>UDLCC1</ProprietaryProductIdentifier>
            <ProductDescription>IBM Storwize V7000 Controller Base SW with 1 Year SW Maintenance, Per Storage Device</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>15005,00</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>3000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>5639-CBC</ProprietaryProductIdentifier>
          <ProductDescription>IBM Spectrum Virtualize Software for Storwize V7000 Controller Software Maint (Reg): 3 Yr</ProductDescription>
          <ProductTypeCode>Software</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>3001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9000</ProprietaryProductIdentifier>
            <ProductDescription>SWMA Renewal Registration</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>3002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>UBKAC5</ProprietaryProductIdentifier>
            <ProductDescription>Base Software Controller Per Storage Device SW Maint 3 year Reg</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>6002,00</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>3003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>UBKEC5</ProprietaryProductIdentifier>
            <ProductDescription>Full Feature Controller Per Storage Device SW Maint 3 year Reg</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>1514,00</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>4000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>5773-PST</ProprietaryProductIdentifier>
          <ProductDescription>Proactive Support for Storage - 3 Year</ProductDescription>
          <ProductTypeCode>Software</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>4001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>5809</ProprietaryProductIdentifier>
            <ProductDescription>Notice doc (www.ibm.biz/tss-agreements)</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>4002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>S1RXGD</ProprietaryProductIdentifier>
            <ProductDescription>Proactive Support per Server (SG01)</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>10764,00</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>5000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>6942-79K</ProprietaryProductIdentifier>
          <ProductDescription>Hardware Maintenance</ProductDescription>
          <ProductTypeCode>Services</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>5001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>TMY7</ProprietaryProductIdentifier>
            <ProductDescription>HWMA IOR SD  24x7 (M19)</ProductDescription>
            <ProductTypeCode>Services</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>6000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>6942-85P</ProprietaryProductIdentifier>
          <ProductDescription>Warranty Service Upgrade</ProductDescription>
          <ProductTypeCode>Services</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>6001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>TYW7</ProprietaryProductIdentifier>
            <ProductDescription>WSU IOR SBD 24x7 (M19)</ProductDescription>
            <ProductTypeCode>Services</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>7000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>6942-CON</ProprietaryProductIdentifier>
          <ProductDescription>Contract Coverage (N/C codes)</ProductDescription>
          <ProductTypeCode>Services</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>7001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>0098</ProprietaryProductIdentifier>
            <ProductDescription>ServiceSuite</ProductDescription>
            <ProductTypeCode>Services</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>8000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>6942-TCS</ProprietaryProductIdentifier>
          <ProductDescription>Terms (N/C codes)</ProductDescription>
          <ProductTypeCode>Services</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>8001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>0055</ProprietaryProductIdentifier>
            <ProductDescription>Prepay Billing 5 Year Term</ProductDescription>
            <ProductTypeCode>Services</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>9000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>6948-56Y</ProprietaryProductIdentifier>
          <ProductDescription>Media Retention</ProductDescription>
          <ProductTypeCode>Services</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>9001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>MRET</ProprietaryProductIdentifier>
            <ProductDescription>HWMA Media Retention</ProductDescription>
            <ProductTypeCode>Services</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>10000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier></OrderedProductIdentifier>
          <ProprietaryProductIdentifier>6948-E35</ProprietaryProductIdentifier>
          <ProductDescription>Global Total Microcode Services</ProductDescription>
          <ProductTypeCode>Services</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>EUR</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>10001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>TGAA</ProprietaryProductIdentifier>
            <ProductDescription>Total Microcode Support-1 annual analysis(ST1)</ProductDescription>